CREATE TABLE benefits_assist_inference_history
(
    id                         BIGINT AUTO_INCREMENT PRIMARY KEY,
    client_name                VARCHAR(255)             NOT NULL,
    client_session_id          VARCHAR(255),
    tracking_id                VARCHAR(255)             NOT NULL,
    submit_date_time           TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id                    VARCHAR(255),
    user_role                  VARCHAR(50),
    conversation_id            VARCHAR(255)             NOT NULL,
    message_id                 VARCHAR(255)             NOT NULL,
    request_date               DATE                     NOT NULL,
    user_query                 TEXT                     NOT NULL,
    response_text              TEXT                     NOT NULL,
    coverage_package_codes     VARCHAR(255)             NOT NULL,
    group_anniversary_date     DATE,
    state_code                 CHAR(20),
    conversation_model_name    VARCHAR(255),
    conversation_model_version VARCHAR(50),
    embedding_model_name       VARCHAR(255),
    embedding_model_version    VARCHAR(50),
    inference_confidence_score VARCHAR(50),
    conversation_intent        VARCHAR(255),
    prompt_tokens              VARCHAR(255),
    completion_tokens          VARCHAR(255),
    total_tokens               VARCHAR(255),
    rag_chunks_retrieved       VARCHAR(255),
    rag_retrieval_score        VARCHAR(255)
);
